In [2]:
import numpy as np
my_arr=np.arange(1000)

In [3]:
data=np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [6]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [7]:
np.empty((1,2,3))

array([[[ 3. , -0.2,  6. ],
        [ 0. , -6. , 13. ]]])

In [8]:
arr1=np.random.rand(2,3)
arr2=np.random.rand(2,3)
arr1>arr2


array([[ True, False, False],
       [False,  True,  True]])

In [9]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5:8]

array([5, 6, 7])

In [12]:
arr[5:8]=12

In [13]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [14]:
arr2d=np.arange(9).reshape(3,-1)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr2d[:2,1:]

array([[1, 2],
       [4, 5]])

In [16]:
names=np.array(['a','b','c'])
data=np.array([4,5,6]).reshape(-1,1).repeat(2,axis=1)

In [17]:
names=='a'

array([ True, False, False])

In [18]:
data[names == "a"]  # return 'true' components

array([[4, 4]])

In [22]:
nsteps=1000
rng=np.random.default_rng(seed=12345)
draws=rng.integers(0,2, size=nsteps)