In [44]:
import numpy as np
rng=np.random.default_rng(seed=12345)

In [13]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
print(np.issubdtype(ints.dtype, np.integer))
print(np.issubdtype(floats.dtype, np.floating))
print(np.issubdtype(floats.dtype, np.number))

True
True
True


In [16]:
arr=np.arange(10).reshape((5,2))
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr.ravel('F')

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [26]:
arr=np.random.rand(10,10,10)
arr.repeat(3, axis=2).shape

(10, 10, 30)

In [29]:
arr=np.arange(10)*100
inds=[7,1,2,6]
arr[inds]

array([700, 100, 200, 600])

In [31]:
arr.take(inds)

array([700, 100, 200, 600])

In [35]:
arr.put(inds,42)

In [43]:
arr=np.random.standard_normal((10,10))
arr.mean(axis=0)
arr.mean(axis=1)

array([ 0.2856086 ,  0.35421114,  0.22600539,  0.00419316,  0.34573251,
        0.18450552, -0.19538892, -0.02073305,  0.06860663, -0.12742303])

In [49]:
arr=rng.standard_normal((3,4,5))
depth_means=arr.mean(-1)
depth_means[np.newaxis,:].shape


(1, 3, 4)